/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as NewRouteImport } from './routes/new'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthenticityRouteImport } from './routes/authenticity'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AdminSyncRouteImport } from './routes/admin.sync'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksSyncStockRouteImport } from './routes/api/public/hooks/sync-stock'
import { Route as ApiPublicAdminImportOnceRouteImport } from './routes/api/public/admin/import-once'

const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticityRoute = AuthenticityRouteImport.update({
  id: '/authenticity',
  path: '/authenticity',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)
const AdminSyncRoute = AdminSyncRouteImport.update({
  id: '/admin/sync',
  path: '/admin/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/admin/pricing',
  path: '/admin/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/admin/import',
  path: '/admin/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncStockRoute = ApiPublicHooksSyncStockRouteImport.update({
  id: '/api/public/hooks/sync-stock',
  path: '/api/public/hooks/sync-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminImportOnceRoute =
  ApiPublicAdminImportOnceRouteImport.update({
    id: '/api/public/admin/import-once',
    path: '/api/public/admin/import-once',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/authenticity': typeof AuthenticityRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/new': typeof NewRoute
  '/shipping': typeof ShippingRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/sync': typeof AdminSyncRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/product/$id': typeof ProductIdRoute
  '/api/public/admin/import-once': typeof ApiPublicAdminImportOnceRoute
  '/api/public/hooks/sync-stock': typeof ApiPublicHooksSyncStockRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/authenticity': typeof AuthenticityRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/new': typeof NewRoute
  '/shipping': typeof ShippingRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/sync': typeof AdminSyncRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/product/$id': typeof ProductIdRoute
  '/api/public/admin/import-once': typeof ApiPublicAdminImportOnceRoute
  '/api/public/hooks/sync-stock': typeof ApiPublicHooksSyncStockRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/authenticity': typeof AuthenticityRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/new': typeof NewRoute
  '/shipping': typeof ShippingRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/sync': typeof AdminSyncRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/product/$id': typeof ProductIdRoute
  '/api/public/admin/import-once': typeof ApiPublicAdminImportOnceRoute
  '/api/public/hooks/sync-stock': typeof ApiPublicHooksSyncStockRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/authenticity'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/new'
    | '/shipping'
    | '/admin/import'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/sync'
    | '/checkout/return'
    | '/product/$id'
    | '/api/public/admin/import-once'
    | '/api/public/hooks/sync-stock'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/authenticity'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/new'
    | '/shipping'
    | '/admin/import'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/sync'
    | '/checkout/return'
    | '/product/$id'
    | '/api/public/admin/import-once'
    | '/api/public/hooks/sync-stock'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/authenticity'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/new'
    | '/shipping'
    | '/admin/import'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/sync'
    | '/checkout/return'
    | '/product/$id'
    | '/api/public/admin/import-once'
    | '/api/public/hooks/sync-stock'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  AuthenticityRoute: typeof AuthenticityRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  NewRoute: typeof NewRoute
  ShippingRoute: typeof ShippingRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminSyncRoute: typeof AdminSyncRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiPublicAdminImportOnceRoute: typeof ApiPublicAdminImportOnceRoute
  ApiPublicHooksSyncStockRoute: typeof ApiPublicHooksSyncStockRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticity': {
      id: '/authenticity'
      path: '/authenticity'
      fullPath: '/authenticity'
      preLoaderRoute: typeof AuthenticityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/admin/sync': {
      id: '/admin/sync'
      path: '/admin/sync'
      fullPath: '/admin/sync'
      preLoaderRoute: typeof AdminSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/admin/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-stock': {
      id: '/api/public/hooks/sync-stock'
      path: '/api/public/hooks/sync-stock'
      fullPath: '/api/public/hooks/sync-stock'
      preLoaderRoute: typeof ApiPublicHooksSyncStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/import-once': {
      id: '/api/public/admin/import-once'
      path: '/api/public/admin/import-once'
      fullPath: '/api/public/admin/import-once'
      preLoaderRoute: typeof ApiPublicAdminImportOnceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutReturnRoute: typeof CheckoutReturnRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutReturnRoute: CheckoutReturnRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  AuthenticityRoute: AuthenticityRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactRoute: ContactRoute,
  NewRoute: NewRoute,
  ShippingRoute: ShippingRoute,
  AdminImportRoute: AdminImportRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminSyncRoute: AdminSyncRoute,
  ProductIdRoute: ProductIdRoute,
  ApiPublicAdminImportOnceRoute: ApiPublicAdminImportOnceRoute,
  ApiPublicHooksSyncStockRoute: ApiPublicHooksSyncStockRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
